Add configuration via block in http support requestToGET
ba-st/Stargate pull request #167
Opened 2023-05-17 15:31 UTC by maximo-torterolo-ambrosini

## header-config-for-tests

Changes by Maximo Torterolo Ambrosini on 2023-05-17

### Changes
* added a message that allows to configure get requests of SingleResourceRESTfulControllerTest with a block in order to avoid long messages extended implementations.
* updated internal implementation of requestToGET messages kind with the new configuration block message.
* added tests for covering language support on quality values, wildcard and empty (header sent but with nothing on it)

[Link to branch](https://github.com/maximo-torterolo-ambrosini/Stargate/tree/header-config-for-tests)

2023-05-17 16:34 UTC, gcotelli requested changes, later dismissed

2023-05-17 16:34 UTC, gcotelli commented on source/Stargate-SUnit-Model/SingleResourceRESTfulControllerTest.class.st
> +				  setAcceptLanguage: aLanguageTag ]
Don't use media type and language tag as the parameter names here, because technically the `Accept` header allows a media range as a value (where a media type definition is a sub-set of the valid values for a media range), and the `Accept-Language` header allows a language range (where a language tag is a sub-set of the valid values).

2023-05-17 17:51 UTC, maximo-torterolo-ambrosini commented on source/Stargate-SUnit-Model/SingleResourceRESTfulControllerTest.class.st
> +				  setAcceptLanguage: aLanguageTag ]
Great. Would you agree if I rename the message to look something more like this?
```st
requestToGETResourceIdentifiedBy: anIdentifier representedBasedOn: aMediaRange fittingIn: aLanguageRange
```

This aligns with the capabilities of the Accept and Accept-Language header, as explained by you. These parameters allow a range of these values.
So it becomes clear that you can pass either a single value or a range of values.

2023-05-17 20:05 UTC, gcotelli commented on source/Stargate-SUnit-Model/SingleResourceRESTfulControllerTest.class.st
> +				  setAcceptLanguage: aLanguageTag ]
Why not `requestToGETResourceIdentifiedBy: anIdentifier acceptingContentMatching: aMediaRange andLanguageMatching: aLanguageRange`

2023-05-17 20:05 UTC, gcotelli commented on source/Stargate-SUnit-Model/SingleResourceRESTfulControllerTest.class.st
> +				  setAcceptLanguage: aLanguageTag ]
If you're in the mood you can also rename parameters in other methods changing `anAcceptHeader` to `aMediaRange`

2023-05-17 20:21 UTC, fortizpenaloza commented on source/Stargate-SUnit-Model/SingleResourceRESTfulControllerTest.class.st
> +				  setAcceptLanguage: aLanguageTag ]
> Why not `requestToGETResourceIdentifiedBy: anIdentifier acceptingContentMatching: aMediaRange andLanguageMatching: aLanguageRange`

I would avoid type names in the message name. Can we avoid the `Language` in `andLanguageMatching`?

2023-05-17 20:46 UTC, fortizpenaloza requested changes

2023-05-17 20:46 UTC, fortizpenaloza commented on source/Stargate-Examples-Tests/SouthAmericanCurrenciesRESTfulControllerTest.class.st
> +	           in: 'de'.
I would perform a set of extract methods for the language tags.

'de' -> unsupportedLanguage
'en' -> english
'es' -> spanish
'es-AR' -> spanishAsUsedInArgentina or argentineSpanish

You can learn more here https://www.w3.org/International/articles/language-tags/

2023-05-17 20:46 UTC, fortizpenaloza commented on source/Stargate-Examples-Tests/SouthAmericanCurrenciesRESTfulControllerTest.class.st
> +						 in: 'de,en;q=0.5,es;=0.6'.
This is called a language priority list. See https://www.w3.org/TR/ltli/#dfn-language-range

2023-05-17 20:46 UTC, fortizpenaloza commented on source/Stargate-SUnit-Model/SingleResourceRESTfulControllerTest.class.st
> +				  setAcceptLanguage: aLanguageTag ]
`requestToGETResourceIdentifiedBy: anIdentifier acceptingContentMatching: aMediaRange and: aLanguageRange`

`requestToGETResourceIdentifiedBy: anIdentifier acceptingContentMatching: aMediaRange andAnyOf: aLanguageRange`

2023-05-19 18:29 UTC, fortizpenaloza approved these changes, later dismissed

2023-05-19 18:29 UTC, fortizpenaloza commented on source/Stargate-Examples-Tests/SouthAmericanCurrenciesRESTfulControllerTest.class.st
> +{ #category : #'private - support' }
Change category to `private - accessing languages`

2023-05-19 18:29 UTC, fortizpenaloza commented on source/Stargate-Examples-Tests/SouthAmericanCurrenciesRESTfulControllerTest.class.st
> +				assert: error allowedLanguageTags includes: 'en-US' asLanguageTag;
Do the extract method for these other language ranges. I already gave you name suggestions

2023-05-19 18:29 UTC, fortizpenaloza commented on source/Stargate-Examples-Tests/SouthAmericanCurrenciesRESTfulControllerTest.class.st
> +	unsupportedLanguage := 'de'.
Do an extract method instead

2023-06-02 13:00 UTC, fortizpenaloza submitted a review, later dismissed

2023-06-02 13:00 UTC, fortizpenaloza commented on source/Stargate-Examples-Tests/SouthAmericanCurrenciesRESTfulControllerTest.class.st
> +	^ 'de,en;q=0.5,es;=0.6'
I think this range is invalid, there's a `q` missing

2023-06-05 20:12 UTC, fortizpenaloza approved these changes

2023-06-05 20:13 UTC, merged