Add a concurrent connections threshold configuration parameter
ba-st/Stargate pull request #184
Opened 2024-03-21 18:49 UTC by gcotelli

This new configuration option will end up controlling the #maximumNumberOfConcurrentConnections parameter in Zinc.

2024-03-21 18:55 UTC, jvanecek submitted a review, later dismissed

2024-03-21 19:02 UTC, ytsejam78 approved these changes, later dismissed

2024-03-21 20:59 UTC, mtabacman requested changes

2024-03-21 20:59 UTC, mtabacman commented on source/Stargate-API-Skeleton-Tests/DelayedRESTfulController.class.st
> +- don't using hypermedia
```suggestion
- not using hypermedia
```

2024-03-22 12:49 UTC, mtabacman approved these changes

2024-03-22 13:01 UTC, merged