Allow using instance creation methods when reading NeoJSON objects
ba-st/Stargate pull request #191
Opened 2024-05-22 19:36 UTC by mtabacman

2024-05-23 20:15 UTC, ytsejam78 commented on source/Stargate-NeoJSON-Extensions/ValidCompleteInstanceMapping.class.st
New name proposal for this class: AbsoluteInstanceMapping
"Absolute" has similar meaning to complete, total, entire.

2024-05-24 17:47 UTC, ytsejam78 submitted a review, later dismissed

2024-05-24 18:03 UTC, gcotelli requested changes

2024-05-24 18:03 UTC, gcotelli commented on source/Stargate-NeoJSON-Extensions/InstanceCreationMapping.class.st
> +I will fail on reading properties of an object if some of the mapped properties are missing in the incoming JSON.
The comment needs an update to better reflect the intention of the class

2024-05-24 18:03 UTC, gcotelli commented on source/Stargate-NeoJSON-Extensions/NeoJSONReader.extension.st
> +NeoJSONReader >> for: schemaName createInstanceUsing: block [
We can change schemaName here to subjectClass, or factory, or something similar because this mapping only works if you use a class as schema. If you pass a symbol like it can be done in other mappings it will not work.

2024-05-24 18:16 UTC, gcotelli approved these changes

2024-05-24 19:17 UTC, merged