Add startup documentation
ba-st/Stargate pull request #90
Opened 2019-12-23 20:34 UTC by gcotelli

Fixes #88

2019-12-24 23:38 UTC, fortizpenaloza requested changes
Good job @gcotelli !

2019-12-24 23:38 UTC, fortizpenaloza commented on docs/Startup.md
> +# Starting up the API
Starting up an API?

2019-12-24 23:38 UTC, fortizpenaloza commented on docs/Startup.md
> +The configuration parameters are passed to `Teapot` so you can configure here any of the options accepted by `Teapot` or `Zinc` servers. The `operations` key is mandatory and it's used for the plugin
```suggestion
The configuration parameters are passed to `Teapot` so you can configure here any of the options accepted by `Teapot` or `Zinc` servers. The `operations` key is mandatory and it's used for the plugin system of Stargate. See [the operations and plugins documentation](Operations.md) to get a list of valid options. For deployment environments, the `jwt` authentication scheme is recommended.
```

2019-12-24 23:38 UTC, fortizpenaloza commented on docs/Startup.md
> +`#serverUrl` parameter is used in Stargate as the base URL in the media controls. So, if you're deploying your API behind a proxy and using an specific domain, this must be reflected in the configura
```suggestion
`#serverUrl` parameter is used as the base URL in the media controls. So, if you're deploying your API behind a proxy and using a specific domain, this must be reflected in the configuration so the media controls links are generated properly. For example `#serverUrl -> 'http://api.example.com'`.
```

2019-12-26 10:48 UTC, gcotelli commented on docs/Startup.md
> +# Starting up the API
```suggestion
# API start up
```

2019-12-26 13:23 UTC, merged